### ISSUE TITLE
m3u header

### ISSUE THREAD

**Issue by pro777s** [jefersonsv/m3uParser#2]
Hello, Jeferson!
Thanks for your m3uParser. 
Please modify the processing of the header of the M3u files. Header so may have parameters, for example:

#EXTM3U url-tvg="http://www.teleguide.info/download/new3/jtv.zip" m3uautoload=1 cache=500 deinterlace=1 tvg-shift=0
#EXTINF:-1 tvg-name="Первый_канал" tvg-logo="Первый канал" group-title="Каналы ЦЭТВ РТРС" ,Первый канал
http://192.168.1.1:4022/udp/225.77.225.1:5000
#EXTINF:-1 tvg-name="Россия_1" tvg-logo="Россия" ,Россия
http://192.168.1.1:4022/udp/225.77.225.2:5000
#EXTINF:-1 tvg-name="Матч!" tvg-logo="Матч ТВ" ,Матч ТВ
http://192.168.1.1:4022/udp/225.77.225.3:5000

**Comment by jefersonsv** [comment]
Hello,

The problem has been fixed. Use the method below to parse:
var contentM3u = M3U.Parse(content);

**Comment by pro777s** [comment]
Hello, Jeferson!
Thanks for update.
However, after installing the nuget package, an error was found: MediaFile for all items is empty.

**Comment by jefersonsv** [comment]
Hello,

The MediaFile object was changed, see the print screen below. Can you send
me the m3u file that you is trying to parse?

[image: image.png]

Thanks

Em dom, 10 de mar de 2019 às 10:09, pro777s <notifications@github.com>
escreveu:

**Comment by pro777s** [comment]
I attach the M3U file for the test.
[rt-udpxy.zip](https://github.com/jefersonsv/m3uParser/files/2951408/rt-udpxy.zip)

**Comment by pro777s** [comment]
There is another problem. The name of your library conflicts with the name of the library in the package "M3UParser" (https://www.nuget.org/packages/M3UParser/). It would be correct if you added postfix, for example '.net', in the name of your library.

**Comment by jefersonsv** [comment]
Hello,

The file was parsed with successfully.
I will rename my github repository to m3uParser.NET

[image: image.png]

Thank you

Em seg, 11 de mar de 2019 às 06:03, pro777s <notifications@github.com>
escreveu:

**Comment by pro777s** [comment]
Hello,

I attach a screenshot with an error.

![m3uParserNet-err](https://user-images.githubusercontent.com/27952867/54190148-544b2380-44c4-11e9-92db-c793c3d652bb.png)

Maybe I'm doing something wrong?
I give an example of the code used:
```
                m3uParser.Model.Extm3u contentM3u = m3uParser.M3U.Parse(m3uContent);
                foreach (m3uParser.Media m3uEntry in contentM3u.Medias)
                {
                    string title = m3uEntry.Title.InnerTitle;
                    if (String.IsNullOrEmpty(title) || String.IsNullOrWhiteSpace(title))
                        title = PlaylistParser.NoNameTitle + " " + ++iNoNameCount;
                    string location = m3uEntry.MediaFile;
                    if (String.IsNullOrEmpty(location) || String.IsNullOrWhiteSpace(location))
                        location = PlaylistParser.StopStreamUrl;
                }

```
This is version 1.0.14 of M3uParser.NET.

**Comment by jefersonsv** [comment]
Hello,

You are right, the MediaFile cannot be parsed in the version 1.0.14

I already fixed it, please update to 1.0.15 to get fixed version.

Thanks,

Em ter, 12 de mar de 2019 às 06:42, pro777s <notifications@github.com>
escreveu:

**Comment by pro777s** [comment]
Bug fixed. Thanks.
Please add extm3u attributes  to the model.
At least the url-tvg attribute.
Desirable add the tvg-shift attribute.

**Comment by jefersonsv** [comment]
The extm3u attributes has been included into the model.

Please update the library on nuget.

Em qua, 13 de mar de 2019 às 07:41, pro777s <notifications@github.com>
escreveu:
