### ISSUE TITLE
The name of your library have a conflict

### ISSUE THREAD

**Issue by pro777s** [jefersonsv/m3uParser#3]
Hello,

There is a problem. The name of your library conflicts with the name of the library in the package "M3UParser" (https://www.nuget.org/packages/M3UParser/). It would be correct if you added postfix, for example '.net', in the name of your library.

**Comment by pro777s** [comment]
For version 1.0.14 of M3uParserNET the problem still exists.

**Comment by jefersonsv** [comment]
The bug has been fixed
